---
title: "What is LANDFIRE"
author: "Sarah Hagen"
toc: true
format: html
---

# What is LANDFIRE?

[LANDFIRE, *Landscape Fire and Resource Management Planning Tools*](https://www.landfire.gov/), is a shared program between the wildland fire management programs of the U.S. Department of Agriculture Forest Service Fire and Aviation branch, and the U.S. Department of the Interior, that provides more than twenty landscape-scale geo-spatial products, 950 vegetation models, and a suite of tools that support all-lands planning, management, and operations. Learn more about the dynamic [LANDFIRE Program](https://landfire.gov/index.php).

## LANDFIRE's Mission

LANDFIRE's mission is to provide agency leaders and managers with a common "all-lands" data set of vegetation and wildland fire/fuels information for strategic fire and resource management planning and analysis.

## What does LANDFIRE provide?

The LANDFIRE Program delivers current, consistent, comprehensive data for the entire United States, including Alaska, Hawai'i, and Puerto Rico and the US Virgin Islands.

This multi-partner program produces current, consistent, comprehensive, geospatial data and databases that describe vegetation, wildland fuel, and fire regimes across the United States and insular areas. Use the [LANDFIRE Technical Documentation](https://pubs.usgs.gov/publication/ofr20231045) to learn how LF creates the data. Use the [LANDFIRE Data Dictionary](https://www.landfire.gov/sites/default/files/documents/LF_Data_Dictionary.pdf) to help understand and locate LANDFIRE information.

**LF products are available by the following groupings:**

-   [Reference](https://landfire.gov/reference) - contribute data or access databases containing contributed disturbance events
-   [Disturbance](https://landfire.gov/disturbance) - a suite of products that categorizes annual and historical disturbance events
-   [Vegetation](https://landfire.gov/vegetation) - products that demonstrate vegetation change across the landscape and models of potential pre-European settlement vegetation systems
-   [Fuel](https://landfire.gov/fuel) - products that demonstrate the composition and characteristics of surface and canopy fuels along with fuel vegetation
-   [Historical Fire Regime](https://landfire.gov/fire-regime) - products that represent pre-European settlement fire frequency and severity
-   [Topographic](https://landfire.gov/topographic) - products that provide geospatial information describing the landscape

### LANDFIRE Data Products by Category

The table below shows a comprehensive list of all the datasets LANDFIRE provides in each category, with links to where you can learn more about each dataset, explore attribute tables, and download data.

| [Vegetation](https://landfire.gov/vegetation) | [Historical Fire Regime](https://landfire.gov/fire-regime) | [Fuel](https://landfire.gov/fuel) | [Disturbance](https://landfire.gov/disturbance) | [Topographic](https://landfire.gov/topographic) | [Reference](https://landfire.gov/reference) |
|------------|------------|------------|------------|------------|------------|
| [Biophysical Settings](https://landfire.gov/vegetation/bps) | [Fire Regime Groups](https://landfire.gov/fire-regime/frg) | [13 Anderson Fire Behavior Fuel Models](https://landfire.gov/fuel/fbfm13) | [Annual Disturbance](https://landfire.gov/disturbance/annualdisturbance) | [Aspect](https://landfire.gov/topographic/aspect) | [Public Events Geodatabase](https://landfire.gov/reference/publicevents) |
| [Environmental Site Potential](https://landfire.gov/vegetation/esp) | [Fire Return Interval](https://landfire.gov/fire-regime/fri) | [40 Scott and Burgan Fire Behavior Fuel Models](https://landfire.gov/fuel/fbfm40) | [Fuel Disturbance](https://landfire.gov/fuel/fdist) | [Elevation](https://landfire.gov/topographic/elevation) | [Public Reference Database (LFRDB)](https://landfire.gov/reference/lfrdb) |
| [Existing Vegetation Cover](https://landfire.gov/vegetation/evc) | [Percent of Low-severity Fire](https://landfire.gov/fire-regime/pls) | [Canadian Forest Fire Danger Rating System](https://landfire.gov/fuel/cffdrs) | [Historical Disturbance](https://landfire.gov/disturbance/hdist) | [Slope](https://landfire.gov/topographic/slope) |  |
| [Existing Vegetation Height](https://landfire.gov/vegetation/evh) | [Percent of Mixed-severity Fire](https://landfire.gov/fire-regime/pms) | [Fuel Characteristic Classification System Fuelbed](https://landfire.gov/fuel/fccs) | [Vegetation Disturbance](https://landfire.gov/disturbance/vdist) |  |  |
| [Existing Vegetation Type](https://landfire.gov/vegetation/evt) | [Percent of Replacement-severity Fire](https://landfire.gov/fire-regime/prs) | [Fuel Disturbance](https://landfire.gov/fuel/fdist) | [Public Events Geodatabase](https://landfire.gov/reference/publicevents) |  |  |
| [Succession Class](https://landfire.gov/vegetation/sclass) |  | [Fuel Loading Models](https://landfire.gov/fuel/flm) | [Forest Transitions Database](https://landfire.gov/disturbance/lf_transitiontbls) |  |  |
| [Vegetation Condition Class](https://landfire.gov/vegetation/vcc) |  | [Canopy Base Height](https://landfire.gov/fuel/cbh) | [Non-forest Vegetation Transitions Database](https://landfire.gov/disturbance/lf_ntransitiontbls) |  |  |
| [Vegetation Departure](https://landfire.gov/vegetation/vdep) |  | [Canopy Bulk Density](https://landfire.gov/fuel/cbd) | [Vegetation Transition Magnitude](https://landfire.gov/disturbance/vtm) |  |  |
|  |  | [Forest Canopy Cover](https://landfire.gov/fuel/cc) |  |  |  |
|  |  | [Forest Canopy Height](https://landfire.gov/fuel/ch) |  |  |  |
|  |  | [Fuel Vegetation Cover](https://landfire.gov/fuel/fvc) |  |  |  |
|  |  | [Fuel Vegetation Height](https://landfire.gov/fuel/fvh) |  |  |  |
|  |  | [Fuel Vegetation Type](https://landfire.gov/fuel/fvt) |  |  |  |

# How Data Products and Information may be used

LANDFIRE offers national-scale spatial products that provide the best available data on vegetation, fuels, fire regimes, and disturbances, supporting landscape assessment, analysis, and management. This data aids in identifying areas with similar characteristics, prioritizing tasks, modeling capacity and potential, and fostering collaboration between landowners through shared data sets and analytics. These products are extensively utilized by land managers for setting priorities, formulating management strategies, and devising action plans. Their applications extend beyond fire management to encompass climate change research, carbon sequestration planning, and habitat analysis. Key applications that use LANDFIRE products are the [Wildland Fire Decision Support System (WFDSS)](https://wfdss.usgs.gov/), [Interagency Fuels Treatment Decision Support System](https://iftdss.firenet.gov/landing_page/), [Terrestrial Condition Assessment](https://terrestrial-condition-assessment-usfs.hub.arcgis.com/), and [Watershed Condition Class](https://www.fs.usda.gov/naturalresources/watershed/condition_framework.shtml).

::: {.callout-note icon="true"}
💡 **A note on application scale** Application scale in LANDFIRE refers to the minimum area size that the data creators aimed to represent accurately for specific applications. It’s not about detail or spatial resolution, but about the usefulness of the product when zoomed in. LANDFIRE provides data for the entire United States, but its application scale is large landscape, regional, national. This means the data is accurate for large geographies, but may not be precise for specific small areas within that geography. Therefore, understanding application scale is crucial when using LANDFIRE products, as it ensures the data represents the overall landscape faithfully for planning or analysis.

For more on application scale, you can read Jim Smith’s [blog post](https://www.conservationgateway.org/ConservationPractices/FireLandscapes/LANDFIRE/Pages/landscape-scale-landfire.aspx) on the topic.
:::

# Product Developments and Improvements

LANDFIRE’s collaborative nature, involving multiple agencies and organizations, has been key to its success. The program has improved relationships among scientists, managers, and the public; increased scientific capacity; and reduced barriers to implementation through a solid scientific foundation.

LANDFIRE has made significant improvements over the years. For example:

-   Updates like the 2014 and 2016 Remap have incorporated landscape changes.

-   LANDFIRE’s Modeling Dynamic Fuels with an Index System ([MoD-FIS](https://www.landfire.gov/fuel/lfmodfis/modfis)) captures seasonal variability in fuels, enhancing fire behavior modeling.

-   The updated Biophysical Settings product suite provides detailed information about vegetation dynamics and fire regimes, supporting comprehensive land management and ecological decision making

# LANDFIRE Versions

Beginning in 2022, LANDFIRE is providing annual updates in which the landscape changes from the previous year are represented in the current year products. You can find the data delivery schedule on the [data page of the LANDFIRE Program website](https://landfire.gov/data#schedule).

LANDFIRE’s version history can be found in the [Version Description table](https://landfire.gov/data/comparison-table) on the LANDFIRE Program website. A [table comparing all LANDFIRE versions](https://landfire.gov/data/comparison-table) from LANDFIRE National (LFc2001) through the current version is also available on the same page. LANDFIRE keeps three versions online for immediate download at all times. Versions not listed can be requested through the [LANDFIRE Helpdesk](https://landfire.gov/contact).

::: {.callout-important icon="true"}
Please visit the [LANDFIRE Program website](https://landfire.gov/data) for the most recent data version and the most up-to-date release schedule.
:::

LANDFIRE data is currently available for the following extents, although not all areas have available data for each version:

-   Conterminous United States (CONUS)

-   Alaska (AK)

-   Hawaii (HI)

-   Insular Areas: American Samoa, Guam, Commonwealth of the Northern Mariana Islands (CNMI), Federated States of Micoronesia, Republic of Palau, Republic of Marshall Islands, Puerto Rico, US Virgin Islands.

## What is The Nature Conservancy’s connection?

The Nature Conservancy (TNC) is a [major partner](https://www.landfire.gov/about-landfire/lfpartners) in the LANDFIRE Program supported by a cooperative agreement through the USDA Forest Service. TNC’s LANDFIRE Team works closely with the LANDFIRE Business Leads, program staff, and other partners to provide support to LANDFIRE users.

LANDFIRE user support can take many forms. Providing this assistance can range from in-person and online workshops to monthly office hours, newsletters and data alerts to learning website development and technical, personalized assistance. TNC’s LANDFIRE team is dedicated to developing current, user-focused LANDFIRE resources that advance natural resource work, amplify the appropriate use of LANDFIRE products, and leverage the collective knowledge of the natural resource community.

[LANDFIRE’s website](https://www.landfire.gov) offers a wealth of resources related to wildland fire and natural resource management. Users can access all LANDFIRE data, resources, applications, and update information on the [LANDFIRE Program website](https://www.landfire.gov).

# Helpful Resources

-   Use the [LANDFIRE Technical Documentation](https://pubs.usgs.gov/publication/ofr20231045) to learn how LANDFIRE creates the data.

-   Use the [LANDFIRE Data Dictionary](https://www.landfire.gov/sites/default/files/documents/LF_Data_Dictionary.pdf) to help understand and locate LANDFIRE information.

-   Use the [LANDFIRE Helpdesk](mailto:helpdesk@landfire.gov) for any questions you have about LANDFIRE products.
