---
title: "LANDFIRE: an introduction"
author: "Sarah Hagen"
toc: true
format: html
---

# What is LANDFIRE?

[LANDFIRE, *Landscape Fire and Resource Management Planning Tools*](https://www.landfire.gov/), is a shared program between the wildland fire management programs of the U.S. Department of Agriculture Forest Service Fire and Aviation branch and the U.S. Department of the Interior. It provides more than twenty landscape-scale geospatial products, 950 vegetation models, and tools supporting all-lands planning, management, and operations.

LANDFIRE's mission is to provide agency leaders and managers with a common ‘all-lands’ dataset of vegetation, wildland fire, and fuels information for strategic fire and resource management planning and analysis. Learn more about LANDFIRE's mission on the [LANDFIRE Program website](https://www.landfire.gov/about-landfire).

# What is The Nature Conservancy’s connection?

The Nature Conservancy (TNC) is a [major partner](https://www.landfire.gov/about-landfire/lfpartners) in the LANDFIRE Program supported by a cooperative agreement through the USDA Forest Service. TNC’s LANDFIRE Team works closely with the LANDFIRE Business Leads, program staff, and other partners to provide support to LANDFIRE users.

LANDFIRE user support can take many forms. Providing this assistance can range from in-person and online workshops to monthly office hours, newsletters and data alerts to learning website development and technical, personalized assistance. Links to where you can find all these information sources and more are at the bottom of each page. TNC’s LANDFIRE team is dedicated to developing current, user-focused LANDFIRE resources that advance natural resource work, amplify the appropriate use of LANDFIRE products, and leverage the collective knowledge of the natural resource community.

[LANDFIRE’s website](https://www.landfire.gov) offers a wealth of resources related to wildland fire and natural resource management. Users can access all LANDFIRE data, resources, applications, and updated information on the [LANDFIRE Program website](https://www.landfire.gov).

# What is the LANDFIRE 101 Learning Website?

Welcome to LANDFIRE 101, an introduction to the essential elements of LANDFIRE — a crucial resource for land management and conservation. This platform is designed to familiarize you with the LANDFIRE Program, [its comprehensive website](https://www.landfire.gov), and some of the invaluable datasets it provides.

LANDFIRE users include district rangers, managers and natural resource specialists who may be tasked with a variety of objectives ranging from managing fuels, wildfires, multiple use requirements, wildlife habitat, and climate change. LANDFIRE products, while not all encompassing, provide a solid foundation from which to build. LANDFIRE aims for consistency and updates most datasets annually. The datasets serve as inputs for programs such as the [Wildland Fire Decision Support System](https://wfdss.usgs.gov/wfdss/WFDSS_Home.shtml) (WFDSS), the [Interagency Fuels Treatment Decision Support System](https://iftdss.firenet.gov/iftdss2/#/landing) (IFTDSS), and [Wildfire Risk to Communities](https://www.wildfirerisk.org). Getting started with LANDFIRE may feel daunting, but this website aims to support anyone getting started with (or diving deeper into) the broad LANDFIRE suite.

::: callout-note
This LANDFIRE 101 learning website serves as a supporting addendum to the [comprehensive LANDFIRE Program website](https://www.landfire.gov). The LANDFIRE 101 learning website can be followed from start-to-finish and provides practical support for LANDFIRE users. This supporting site should be used in conjunction with (not instead of) the [LANDFIRE Program website](https://www.landfire.gov). As such, we provide essentials for getting started with using and applying LANDFIRE products. Each page provides multiple opportunities for understanding and exploring these data further on the [LANDFIRE Program website](https://www.landfire.gov).
:::

# What you will learn

Our LANDFIRE 101 learning website provides a foundation for:

-   Basic background information about LANDFIRE vegetation and fuels datasets

-   Important attributes of each dataset

-   How and where to download each product

-   Examples of how these products are commonly used

-   How to properly use and apply LANDFIRE Products and avoid common misapplications of the data


Whether you are a novice or seeking to deepen your expertise, this training platform provides the insights and practical skills necessary for leveraging LANDFIRE data in your projects. We invite you to join us and discover how these powerful tools can support your endeavors in land management and beyond.
