---
title: "LANDFIRE Datasets: An Overview"
author: "Sarah Hagen"
toc: true
format: html
---

In our work, we frequently utilize various vegetation and fire regime datasets to gain a deeper understanding of certain landscapes. Key datasets such as Biophysical Settings, Existing Vegetation, and Succession Class are integrated to create the Vegetation Departure (VDEP) product. This section of the website will give you an overview of these essential datasets, along with links to additional information and download options for your use.

Here, you’ll learn how to access and make good use of these datasets. We’ll walk you through how to download each one and share real-life examples of how they can be applied. We’ll also introduce you to other helpful tools that can improve your work, making this a complete resource for everything LANDFIRE-related.

# A Word About Vegetation Classifications

LANDFIRE adopted NatureServe’s [Ecological Systems](https://www.natureserve.org/publications/ecological-systems-united-states) (ES) classification in 2004. At that time, it was the only consistent classification available continent-wide, and its ecological foundation fit the needs of the project as designed. Ecological Systems is currently used in the Existing Vegetation Type (EVT) and Biophysical Settings (BpS) spatial layers, the Biophysical Settings Models and Descriptions products and Historic Fire Regime. Three other classifications are provided as attributes of the EVT layer: National Vegetation Classification Group (NVCG), National Vegetation Classification Macrogroup (NVCM) and Society of American Foresters/Society of Range Management (SAF/SRM) Cover Type. The only classification that is directly mapped by LANDFIRE at the present time is Ecological Systems. NVCG is provided as a separate spatial layer in LF2016 but it and SAF/SRM attributes are created using a crosswalk with ES. Since the National Vegetation Classification is hierarchical, NVCM is created by rolling-up NVCG into the next highest level of the classification.

# What you will learn in this section

- A brief overview of some commonly used datasets

- How to download and access LANDFIRE datasets

- How these key LANDFIRE datasets are linked to one another
